// Curated allow-list of the Xero account codes that staff may pick on an expense
// claim. The expense form is narrowed to exactly these (live name + GST type
// still come from Xero); order here is the order shown in the dropdown.
//
// To change which accounts appear, edit this list (code + name) and redeploy.
export const EXPENSE_ACCOUNTS: { code: string; name: string }[] = [
  { code: "62020", name: "Bldg-General Maintenance" },
  { code: "62030", name: "Bldg-Cleaning" },
  { code: "63011", name: "Worship-Training" },
  { code: "63022", name: "Worship-Hospitality" },
  { code: "63023", name: "Worship-Equipment Maintenance" },
  { code: "63031", name: "Worship-Events" },
  { code: "63050", name: "Worship-MISC" },
  { code: "63112", name: "HmGrp-Leaders" },
  { code: "63141", name: "HmGrp-Events" },
  { code: "63144", name: "HmGrp-Ladies Ministry" },
  { code: "63150", name: "HmGrp-Misc." },
  { code: "63221", name: "ChrisEd-Resources" },
  { code: "63225", name: "ChrisEd-Alpha" },
  { code: "63250", name: "ChrisEd-Misc." },
  { code: "63411", name: "1830-Events" },
  { code: "63414", name: "1830-Leaders" },
  { code: "63418", name: "1830-Camps" },
  { code: "63421", name: "1830-Misc." },
  { code: "63512", name: "Kids-Leaders" },
  { code: "63521", name: "Kids-Preschool Ministry" },
  { code: "63522", name: "Kids-Primary Ministry" },
  { code: "63525", name: "Kids-Events" },
  { code: "63531", name: "Kids-Kids Camp" },
  { code: "63546", name: "Kids-Sponsor Child" },
  { code: "63550", name: "Kids-Misc." },
  { code: "63612", name: "Yth-Leaders" },
  { code: "63621", name: "Yth-Friday Night Program" },
  { code: "63631", name: "Yth-Youth Camp" },
  { code: "63644", name: "Yth-Outreach" },
  { code: "63650", name: "Yth-Misc." },
  { code: "63690", name: "Yth-Sp.Fund Expenses" },
  { code: "63760", name: "Chinese Ministry - Expenses" },
  { code: "64019", name: "P&I-Healing Rooms" },
  { code: "64022", name: "P&I-Ministry Programs" },
  { code: "64026", name: "P&I-Events" },
  { code: "64027", name: "P&I-Leaders" },
  { code: "64101", name: "Media-Software Maint." },
  { code: "64102", name: "Media-Hardware Maint." },
  { code: "64105", name: "Media-Training & Hospitality" },
  { code: "64106", name: "Media-Misc." },
  { code: "67015", name: "Past-Elders Misc." },
  { code: "67032", name: "Past-Conference" },
  { code: "67033", name: "Past-Staff/SLT Retreat" },
  { code: "67035", name: "Past-Hospitality" },
  { code: "67036", name: "Past-Staff Development" },
  { code: "67046", name: "Past-Interchurch Partnership" },
  { code: "67047", name: "Past-Senior Pastor Discretionary" },
  { code: "67090", name: "Past-Misc." },
  { code: "67092", name: "Past-SLT Approved Expenses" },
  { code: "67110", name: "Ps.Serv-Wedd Bap Dedic Funeral" },
  { code: "67116", name: "Ps.Serv-Special Sundays" },
  { code: "67118", name: "Ps.Serv-Church Anniversary" },
  { code: "67119", name: "Ps.Serv-Christmas Blessing" },
  { code: "67120", name: "Ps.Serv-Orientation" },
  { code: "67130", name: "Ps.Serv-Disposables" },
  { code: "67131", name: "Ps.Serv-Kitchen Operations" },
  { code: "67160", name: "Ps.Serv-Misc." },
  { code: "67161", name: "Ps.Serv-Speakers" },
  { code: "67162", name: "Ps.Serv-Sunday Service" },
  { code: "67164", name: "Ps.Serv-Hospitality Leaders" },
  { code: "67172", name: "Ps.Serv-Leaders Churchwide" },
  { code: "67173", name: "Ps.Serv-Churchwide Events" },
  { code: "67174", name: "Ps.Serv-REACH" },
  { code: "68023", name: "AdmFin-Stationery" },
  { code: "68025", name: "AdmFin-Office Communications" },
  { code: "68026", name: "AdmFin-Utilities Rates & Taxes" },
  { code: "68044", name: "AdmFin-Ministries Venue Hire" },
  { code: "68200", name: "AdmFin-Motor Vehicle Expenses" },
  { code: "68235", name: "AdmFin-Admin & Support Outsouced" },
  { code: "68243", name: "Ps.Serv-Sunday Food Sales" },
  { code: "68300", name: "AdmFin-Misc." },
  { code: "69212", name: "Misn-[Administration] Mission Month Sundays" },
  { code: "69218", name: "Misn-[Administration] Training / Education" },
  { code: "69220", name: "Misn-[Administration] General Miscellaneous" },
  { code: "69271", name: "Misn-[Organisation] General - Entrust Foundation" },
  { code: "69272", name: "Misn-[Mission Trip] Cambodia" },
  { code: "69315", name: "Misn-[Project] Apostolic Fund" },
  { code: "69332", name: "Misn-IPIN-Sp.Fund Expense" },
  { code: "69351", name: "Misn-[Missionary] Jeannet Mckee" },
  { code: "69358", name: "Misn-[Organisation] Online - Online Bible College" },
  { code: "69372", name: "Misn-[Project] Mercy Fund" },
  { code: "69376", name: "Misn-[Project] Australia - others" },
  { code: "69378", name: "Misn-[Project] Australia - Christmas Blessings" },
  { code: "69384", name: "Misn-[Missionary] China - Ruth Zhang" },
];

export const EXPENSE_ACCOUNT_CODES = new Set(EXPENSE_ACCOUNTS.map((a) => a.code));
